// Static Products Database for Medi Teck Engineering
// This file holds the complete hierarchical catalog of 28 medical engineering products.

window.PRODUCTS_DATA = [
    // === CATEGORY A: MEDICAL GASES SYSTEM ===
    {
        "id": "1",
        "name": "Central Copper Pipeline System",
        "category": "medical-gases-system",
        "subcategory": "Central Copper Pipeline System",
        "slug": "central-copper-pipeline-system",
        "description": "Medical grade degreased copper pipes and fittings manufactured under strict quality standards. Essential for reliable medical gas distribution.",
        "image_url": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&h=400&fit=crop",
        "features": ["High purity degreased copper", "BS EN 13348 compliant", "Leak-proof brazed joints", "Corrosion resistant surfaces"],
        "status": "active",
        "display_order": 1
    },
    {
        "id": "2",
        "name": "Oxygen Manifold System (Automatic)",
        "category": "medical-gases-system",
        "subcategory": "Manifold System",
        "slug": "oxygen-manifold-system-automatic",
        "description": "High-pressure automatic oxygen manifold system with smart electronic changeover to ensure 100% uninterrupted oxygen supply.",
        "image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop",
        "features": ["Smart electronic changeover", "Dual stage pressure regulator", "High pressure flexible copper tails", "Audio-visual status indicators"],
        "status": "active",
        "display_order": 2
    },
    {
        "id": "3",
        "name": "Oxygen Manifold System (Manual)",
        "category": "medical-gases-system",
        "subcategory": "Manifold System",
        "slug": "oxygen-manifold-system-manual",
        "description": "Reliable manual oxygen manifold system featuring robust valves and heavy-duty regulators for safe cylinder bank switching.",
        "image_url": "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=600&h=400&fit=crop",
        "features": ["Heavy-duty brass construction", "Manual isolation valves", "Clear pressure indicators", "Cost-effective safety design"],
        "status": "active",
        "display_order": 3
    },
    {
        "id": "4",
        "name": "Nitrous Manifold System (Automatic)",
        "category": "medical-gases-system",
        "subcategory": "Manifold System",
        "slug": "nitrous-manifold-system-automatic",
        "description": "Automatic changeover Nitrous Oxide manifold system, designed to handle nitrous cylinder pressure changes with micro-second accuracy.",
        "image_url": "https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=600&h=400&fit=crop",
        "features": ["Smart digital controller", "Integrated pressure relief valves", "Auto-switchover cylinder banks", "Wall-mounted space saving cabinet"],
        "status": "active",
        "display_order": 4
    },
    {
        "id": "5",
        "name": "Nitrous Manifold System (Manual)",
        "category": "medical-gases-system",
        "subcategory": "Manifold System",
        "slug": "nitrous-manifold-system-manual",
        "description": "Manually operated Nitrous Oxide manifold system with durable brass headers, built for long-term clinical safety.",
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&h=400&fit=crop",
        "features": ["Durable copper/brass headers", "Manual lever switch control", "High-accuracy dual gauges", "Pre-tested safety valves"],
        "status": "active",
        "display_order": 5
    },
    {
        "id": "6",
        "name": "Oxygen Generation Plant",
        "category": "medical-gases-system",
        "subcategory": "Central Medical Gas Plants",
        "slug": "oxygen-generation-plant",
        "description": "On-site Pressure Swing Adsorption (PSA) oxygen generation plant. Produces high-purity medical oxygen from compressed ambient air.",
        "image_url": "https://images.unsplash.com/photo-1616391182219-e080b4d1043a?w=600&h=400&fit=crop",
        "features": ["93% ± 3% purity output", "Energy efficient operation", "PLC automated controls", "Integrated purity analyzer"],
        "status": "active",
        "display_order": 6
    },
    {
        "id": "7",
        "name": "Air Compressor Plant",
        "category": "medical-gases-system",
        "subcategory": "Central Medical Gas Plants",
        "slug": "air-compressor-plant",
        "description": "Multi-stage oil-free medical air compressor plant with desiccant dryers and high-efficiency filtration to provide pure breathing air.",
        "image_url": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&h=400&fit=crop",
        "features": ["100% oil-free compression", "Desiccant air dryers", "Multi-stage bacterial filtration", "PLC auto-alternation control"],
        "status": "active",
        "display_order": 7
    },
    {
        "id": "8",
        "name": "Vacuum Plant",
        "category": "medical-gases-system",
        "subcategory": "Central Medical Gas Plants",
        "slug": "vacuum-plant",
        "description": "High-efficiency duplex/triplex medical vacuum plant with chemical-resistant pumps, dual bacterial filters, and automatic receivers.",
        "image_url": "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&h=400&fit=crop",
        "features": ["High efficiency vacuum pumps", "Duplex bacterial filters", "ASME receiver tanks", "Touch-screen system monitor"],
        "status": "active",
        "display_order": 8
    },
    {
        "id": "9",
        "name": "AGSS System",
        "category": "medical-gases-system",
        "subcategory": "Central Medical Gas Plants",
        "slug": "agss-system",
        "description": "Anesthetic Gas Scavenging System (AGSS) to safely remove waste anesthetic gas mixtures from operating theaters.",
        "image_url": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop",
        "features": ["High-capacity blower pumps", "Adjustable flow regulator", "Anti-spill theater terminals", "ISO 7396-2 safety compliant"],
        "status": "active",
        "display_order": 9
    },
    {
        "id": "10",
        "name": "Bed Head Units",
        "category": "medical-gases-system",
        "subcategory": "Bed Head Units",
        "slug": "bed-head-units",
        "description": "Modern, ergonomic bed head console panels integrated with gas outlets, electrical sockets, nurse call systems, and direct/indirect lighting.",
        "image_url": "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&h=400&fit=crop",
        "features": ["Extruded aluminum profiles", "Integrated gas & electric slots", "Sleek, low-profile design", "Direct/indirect LED lights"],
        "status": "active",
        "display_order": 10
    },
    {
        "id": "11",
        "name": "Single Arm Pendant",
        "category": "medical-gases-system",
        "subcategory": "Ceiling Pendants",
        "slug": "single-arm-pendant",
        "description": "Ceiling-mounted single-arm surgical pendant providing flexible mounting for equipment, medical gas outlets, and power supply in OTs and ICUs.",
        "image_url": "https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&h=400&fit=crop",
        "features": ["330-degree arm rotation", "Pneumatic or mechanical brakes", "High load capacity shelves", "Modular gas/electric console"],
        "status": "active",
        "display_order": 11
    },
    {
        "id": "12",
        "name": "Double Arm Pendant",
        "category": "medical-gases-system",
        "subcategory": "Ceiling Pendants",
        "slug": "double-arm-pendant",
        "description": "Heavy-duty dual-arm ceiling pendant offering maximum reach, flexibility, and equipment support for complex surgical and intensive care environments.",
        "image_url": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop",
        "features": ["Dual articulating arms", "Modular console interface", "Pre-piped and pre-wired internally", "Precision gas bearings"],
        "status": "active",
        "display_order": 12
    },
    {
        "id": "13",
        "name": "Rigid Pendant",
        "category": "medical-gases-system",
        "subcategory": "Ceiling Pendants",
        "slug": "rigid-pendant",
        "description": "Robust fixed-height ceiling pendant, providing space-saving access to essential medical gases and power in emergency bays.",
        "image_url": "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&h=400&fit=crop",
        "features": ["Fixed heavy-duty steel shaft", "Compact vertical console", "High-capacity gas outlets", "Low maintenance design"],
        "status": "active",
        "display_order": 13
    },

    // === CATEGORY B: MEDICAL GASES PRIMARY & SECONDARY ACCESSORIES ===
    {
        "id": "14",
        "name": "Single Gas Zone Service Unit",
        "category": "primary-secondary-accessories",
        "subcategory": "Area Valve Service Unit",
        "slug": "single-gas-zone-service-unit",
        "description": "Visual and physical zone isolation valve box for single medical gas pipeline, featuring emergency pull-to-shut handle.",
        "image_url": "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=600&h=400&fit=crop",
        "features": ["Lockable emergency window", "Integrated physical gauge", "Leak-proof valve design", "Clear color-coded label"],
        "status": "active",
        "display_order": 14
    },
    {
        "id": "15",
        "name": "Multi Level Area Valve Service Unit",
        "category": "primary-secondary-accessories",
        "subcategory": "Area Valve Service Unit",
        "slug": "multi-level-area-valve-service-unit",
        "description": "Multi-tier area valve service unit containing isolation valves and monitoring gauges for 2 to 6 medical gas pipelines in a single console.",
        "image_url": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&h=400&fit=crop",
        "features": ["Multi-tier compact cabinet", "Individual zone isolation", "Dual physical pressure sensors", "Physical override layout"],
        "status": "active",
        "display_order": 15
    },
    {
        "id": "16",
        "name": "Multi Gas Alarm (Digital Display)",
        "category": "primary-secondary-accessories",
        "subcategory": "Alarm Systems",
        "slug": "multi-gas-alarm-digital",
        "description": "Real-time digital gas alarm panel designed to monitor line pressure for up to 6 medical gases with clear alphanumeric readings.",
        "image_url": "https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=600&h=400&fit=crop",
        "features": ["High brightness LED readouts", "Adjustable pressure thresholds", "Audio-visual alarm mute", "BMS network connectivity"],
        "status": "active",
        "display_order": 16
    },
    {
        "id": "17",
        "name": "Single Gas Alarm (Digital Display)",
        "category": "primary-secondary-accessories",
        "subcategory": "Alarm Systems",
        "slug": "single-gas-alarm-digital",
        "description": "Dedicated single gas electronic alarm panel with precision pressure transducer input and local numerical display.",
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&h=400&fit=crop",
        "features": ["Microprocessor controls", "Digital numerical panel", "High/Low warning trigger", "Sealed membrane keyboard"],
        "status": "active",
        "display_order": 17
    },
    {
        "id": "18",
        "name": "Single Gas Alarm (Simple)",
        "category": "primary-secondary-accessories",
        "subcategory": "Alarm Systems",
        "slug": "single-gas-alarm-simple",
        "description": "Traditional LED indicator medical gas alarm, using high-reliability pressure switches to warn clinicians of pressure drops.",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=400&fit=crop",
        "features": ["Dual LED indicator lamps", "Audible piezo buzzer", "Simple terminal switch input", "Compact flush-mount build"],
        "status": "active",
        "display_order": 18
    },
    {
        "id": "19",
        "name": "Touch Screen Alarm (Premium)",
        "category": "primary-secondary-accessories",
        "subcategory": "Alarm Systems",
        "slug": "touch-screen-alarm-premium",
        "description": "State-of-the-art interactive touch-screen alarm system. Monitors gas pressure, flow rates, and historical logs with graphical UI.",
        "image_url": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop",
        "features": ["7-inch capacitive touch LCD", "Live pressure trend graphing", "Automatic email/SMS alerts", "Modbus TCP/IP support"],
        "status": "active",
        "display_order": 19
    },
    {
        "id": "20",
        "name": "Oxygen Flowmeter",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "oxygen-flowmeter",
        "description": "Precision medical oxygen flowmeter with humidifier bottle. Designed for accurate regulation and delivery of oxygen therapy to patients.",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=400&fit=crop",
        "features": ["High-impact polycarbonate tube", "Calibrated flow regulation", "Autoclavable humidifier bottle", "Double-sealed inlet stem"],
        "status": "active",
        "display_order": 20
    },
    {
        "id": "21",
        "name": "Humidifier Bottle",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "humidifier-bottle",
        "description": "High-capacity autoclavable medical humidifier bottle with bubble diffuser, providing silent humidification for oxygen therapy.",
        "image_url": "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&h=400&fit=crop",
        "features": ["Autoclavable polycarbonate body", "Integrated brass fittings", "Silent bubble diffuser", "Over-pressure safety valve"],
        "status": "active",
        "display_order": 21
    },
    {
        "id": "22",
        "name": "Vacuum Controller",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "vacuum-controller",
        "description": "Precision surgical vacuum controller regulator with fine suction gauge control and emergency full-suction override.",
        "image_url": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop",
        "features": ["REG/OFF/MAX toggle control", "Fine vacuum control gauge", "High accuracy scale (mmHg)", "Internal safety filter"],
        "status": "active",
        "display_order": 22
    },
    {
        "id": "23",
        "name": "Suction Injector",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "suction-injector",
        "description": "Venturi-effect suction injector driven by compressed air or oxygen, providing reliable suction where central vacuum is unavailable.",
        "image_url": "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&h=400&fit=crop",
        "features": ["Venturi-effect mechanism", "Dual drive compatibility", "Integrated vacuum gauge", "Compact chrome plated body"],
        "status": "active",
        "display_order": 23
    },
    {
        "id": "24",
        "name": "Suction Jar",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "suction-jar",
        "description": "Heavy-duty autoclavable surgical suction collection jar featuring an automatic anti-overflow safety float valve.",
        "image_url": "https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&h=400&fit=crop",
        "features": ["2000ml / 4000ml capacities", "Autoclavable PSU/Polycarbonate", "Anti-overflow safety float", "Flexible wall bracket hanger"],
        "status": "active",
        "display_order": 24
    },
    {
        "id": "25",
        "name": "Silicone Tube",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "silicone-tube",
        "description": "Medical-grade platinum cured translucent silicone tubing, ideal for clinical suction, surgical drains, and fluid transfer.",
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&h=400&fit=crop",
        "features": ["Platinum-cured medical grade", "Non-toxic & odor-free", "Autoclavable up to 134°C", "High flexibility & tear strength"],
        "status": "active",
        "display_order": 25
    },
    {
        "id": "26",
        "name": "Oxygen Cylinder Regulator",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "oxygen-cylinder-regulator",
        "description": "Durable two-stage oxygen cylinder pressure regulator. Provides safe and stable flow reduction from high pressure cylinders to clinical applications.",
        "image_url": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&h=400&fit=crop",
        "features": ["Brass body chrome plated", "Clear pressure indicators", "Safety relief valve integrated", "Durable neoprene diaphragm"],
        "status": "active",
        "display_order": 26
    },
    {
        "id": "27",
        "name": "Single Stage Regulator",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "single-stage-regulator",
        "description": "Compact single-stage pressure regulator designed for primary reduction of medical gases from bulk storage or cylinders.",
        "image_url": "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=600&h=400&fit=crop",
        "features": ["Extremely compact envelope", "Teflon encapsulation seat", "Easy pressure setting dial", "Built-in line inlet filter"],
        "status": "active",
        "display_order": 27
    },
    {
        "id": "28",
        "name": "Multi Stage Regulator",
        "category": "primary-secondary-accessories",
        "subcategory": "Medical Gas Accessories",
        "slug": "multi-stage-regulator",
        "description": "Ultra-precise dual-stage regulator offering highly stable output pressure even as input cylinder pressure drops.",
        "image_url": "https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=600&h=400&fit=crop",
        "features": ["Precision dual stage design", "Constant pressure discharge", "Sintered metal inlet filter", "Approved for high pressure medical O2"],
        "status": "active",
        "display_order": 28
    }
];
